// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: v1/messages.proto

package messagesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputType int32

const (
	OutputType_OUTPUT_TYPE_UNSPECIFIED OutputType = 0
	OutputType_OUTPUT_TYPE_STDOUT      OutputType = 1
	OutputType_OUTPUT_TYPE_STDERR      OutputType = 2
)

// Enum value maps for OutputType.
var (
	OutputType_name = map[int32]string{
		0: "OUTPUT_TYPE_UNSPECIFIED",
		1: "OUTPUT_TYPE_STDOUT",
		2: "OUTPUT_TYPE_STDERR",
	}
	OutputType_value = map[string]int32{
		"OUTPUT_TYPE_UNSPECIFIED": 0,
		"OUTPUT_TYPE_STDOUT":      1,
		"OUTPUT_TYPE_STDERR":      2,
	}
)

func (x OutputType) Enum() *OutputType {
	p := new(OutputType)
	*p = x
	return p
}

func (x OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_messages_proto_enumTypes[0].Descriptor()
}

func (OutputType) Type() protoreflect.EnumType {
	return &file_v1_messages_proto_enumTypes[0]
}

func (x OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputType.Descriptor instead.
func (OutputType) EnumDescriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ImplantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2ServerId    string                 `protobuf:"bytes,1,opt,name=c2_server_id,json=c2ServerId,proto3" json:"c2_server_id,omitempty"`
	InternalId    string                 `protobuf:"bytes,2,opt,name=internal_id,json=internalId,proto3" json:"internal_id,omitempty"`
	C2Type        string                 `protobuf:"bytes,3,opt,name=c2_type,json=c2Type,proto3" json:"c2_type,omitempty"`
	PayloadType   string                 `protobuf:"bytes,4,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Hostname      string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Sleep         int32                  `protobuf:"varint,8,opt,name=sleep,proto3" json:"sleep,omitempty"`
	Jitter        int32                  `protobuf:"varint,9,opt,name=jitter,proto3" json:"jitter,omitempty"`
	Os            string                 `protobuf:"bytes,10,opt,name=os,proto3" json:"os,omitempty"`
	Pid           int32                  `protobuf:"varint,11,opt,name=pid,proto3" json:"pid,omitempty"`
	Architecture  string                 `protobuf:"bytes,12,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Process       string                 `protobuf:"bytes,13,opt,name=process,proto3" json:"process,omitempty"`
	Username      string                 `protobuf:"bytes,14,opt,name=username,proto3" json:"username,omitempty"`
	Ip            string                 `protobuf:"bytes,15,opt,name=ip,proto3" json:"ip,omitempty"`
	ExternalIp    string                 `protobuf:"bytes,16,opt,name=external_ip,json=externalIp,proto3" json:"external_ip,omitempty"`
	Domain        string                 `protobuf:"bytes,17,opt,name=domain,proto3" json:"domain,omitempty"`
	LastCheckin   string                 `protobuf:"bytes,18,opt,name=last_checkin,json=lastCheckin,proto3" json:"last_checkin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplantRequest) Reset() {
	*x = ImplantRequest{}
	mi := &file_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplantRequest) ProtoMessage() {}

func (x *ImplantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplantRequest.ProtoReflect.Descriptor instead.
func (*ImplantRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ImplantRequest) GetC2ServerId() string {
	if x != nil {
		return x.C2ServerId
	}
	return ""
}

func (x *ImplantRequest) GetInternalId() string {
	if x != nil {
		return x.InternalId
	}
	return ""
}

func (x *ImplantRequest) GetC2Type() string {
	if x != nil {
		return x.C2Type
	}
	return ""
}

func (x *ImplantRequest) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *ImplantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImplantRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ImplantRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ImplantRequest) GetSleep() int32 {
	if x != nil {
		return x.Sleep
	}
	return 0
}

func (x *ImplantRequest) GetJitter() int32 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

func (x *ImplantRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ImplantRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ImplantRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *ImplantRequest) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *ImplantRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ImplantRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ImplantRequest) GetExternalIp() string {
	if x != nil {
		return x.ExternalIp
	}
	return ""
}

func (x *ImplantRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ImplantRequest) GetLastCheckin() string {
	if x != nil {
		return x.LastCheckin
	}
	return ""
}

type ImplantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplantResponse) Reset() {
	*x = ImplantResponse{}
	mi := &file_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplantResponse) ProtoMessage() {}

func (x *ImplantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplantResponse.ProtoReflect.Descriptor instead.
func (*ImplantResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{2}
}

type ProxyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Host           string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port           int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Note           string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	RemoteHostname string                 `protobuf:"bytes,6,opt,name=remote_hostname,json=remoteHostname,proto3" json:"remote_hostname,omitempty"`
	Username       string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Password       string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	C2ServerId     string                 `protobuf:"bytes,9,opt,name=c2_server_id,json=c2ServerId,proto3" json:"c2_server_id,omitempty"`
	InternalId     string                 `protobuf:"bytes,10,opt,name=internal_id,json=internalId,proto3" json:"internal_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProxyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProxyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProxyRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProxyRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *ProxyRequest) GetRemoteHostname() string {
	if x != nil {
		return x.RemoteHostname
	}
	return ""
}

func (x *ProxyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProxyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProxyRequest) GetC2ServerId() string {
	if x != nil {
		return x.C2ServerId
	}
	return ""
}

func (x *ProxyRequest) GetInternalId() string {
	if x != nil {
		return x.InternalId
	}
	return ""
}

type ProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{4}
}

type FileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filename          string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Bucket            string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path              string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	InternalTaskId    string                 `protobuf:"bytes,4,opt,name=internal_task_id,json=internalTaskId,proto3" json:"internal_task_id,omitempty"`
	C2ServerId        string                 `protobuf:"bytes,5,opt,name=c2_server_id,json=c2ServerId,proto3" json:"c2_server_id,omitempty"`
	InternalImplantId string                 `protobuf:"bytes,6,opt,name=internal_implant_id,json=internalImplantId,proto3" json:"internal_implant_id,omitempty"`
	UploadFileId      string                 `protobuf:"bytes,7,opt,name=upload_file_id,json=uploadFileId,proto3" json:"upload_file_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRequest) GetInternalTaskId() string {
	if x != nil {
		return x.InternalTaskId
	}
	return ""
}

func (x *FileRequest) GetC2ServerId() string {
	if x != nil {
		return x.C2ServerId
	}
	return ""
}

func (x *FileRequest) GetInternalImplantId() string {
	if x != nil {
		return x.InternalImplantId
	}
	return ""
}

func (x *FileRequest) GetUploadFileId() string {
	if x != nil {
		return x.UploadFileId
	}
	return ""
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *FileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type C2TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2ServerId    string                 `protobuf:"bytes,1,opt,name=c2_server_id,json=c2ServerId,proto3" json:"c2_server_id,omitempty"`
	C2TaskId      string                 `protobuf:"bytes,2,opt,name=c2_task_id,json=c2TaskId,proto3" json:"c2_task_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2TaskStatusRequest) Reset() {
	*x = C2TaskStatusRequest{}
	mi := &file_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2TaskStatusRequest) ProtoMessage() {}

func (x *C2TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*C2TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *C2TaskStatusRequest) GetC2ServerId() string {
	if x != nil {
		return x.C2ServerId
	}
	return ""
}

func (x *C2TaskStatusRequest) GetC2TaskId() string {
	if x != nil {
		return x.C2TaskId
	}
	return ""
}

func (x *C2TaskStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *C2TaskStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type C2TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2TaskStatusResponse) Reset() {
	*x = C2TaskStatusResponse{}
	mi := &file_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2TaskStatusResponse) ProtoMessage() {}

func (x *C2TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*C2TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{8}
}

type SettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2ServerId    string                 `protobuf:"bytes,1,opt,name=c2_server_id,json=c2ServerId,proto3" json:"c2_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsRequest) Reset() {
	*x = SettingsRequest{}
	mi := &file_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsRequest) ProtoMessage() {}

func (x *SettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsRequest.ProtoReflect.Descriptor instead.
func (*SettingsRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *SettingsRequest) GetC2ServerId() string {
	if x != nil {
		return x.C2ServerId
	}
	return ""
}

type SettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	CaCertificate string                 `protobuf:"bytes,7,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,8,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Token         string                 `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
	Certificate   string                 `protobuf:"bytes,10,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsResponse) Reset() {
	*x = SettingsResponse{}
	mi := &file_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsResponse) ProtoMessage() {}

func (x *SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsResponse.ProtoReflect.Descriptor instead.
func (*SettingsResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *SettingsResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SettingsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SettingsResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SettingsResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SettingsResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SettingsResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SettingsResponse) GetCaCertificate() string {
	if x != nil {
		return x.CaCertificate
	}
	return ""
}

func (x *SettingsResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SettingsResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SettingsResponse) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

type TaskRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InternalId string                 `protobuf:"bytes,1,opt,name=internal_id,json=internalId,proto3" json:"internal_id,omitempty"`
	C2ServerId string                 `protobuf:"bytes,2,opt,name=c2_server_id,json=c2ServerId,proto3" json:"c2_server_id,omitempty"`
	Status     string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// This field should contain the internal representation of whatever parameters you have set.
	OriginalParams string `protobuf:"bytes,4,opt,name=original_params,json=originalParams,proto3" json:"original_params,omitempty"`
	// This field should contain the human readable representation of the parameters, if available.
	DisplayParams     string `protobuf:"bytes,5,opt,name=display_params,json=displayParams,proto3" json:"display_params,omitempty"`
	TimeStarted       string `protobuf:"bytes,6,opt,name=time_started,json=timeStarted,proto3" json:"time_started,omitempty"`
	TimeCompleted     string `protobuf:"bytes,7,opt,name=time_completed,json=timeCompleted,proto3" json:"time_completed,omitempty"`
	CommandName       string `protobuf:"bytes,8,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	Operator          string `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	InternalImplantId string `protobuf:"bytes,10,opt,name=internal_implant_id,json=internalImplantId,proto3" json:"internal_implant_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *TaskRequest) GetInternalId() string {
	if x != nil {
		return x.InternalId
	}
	return ""
}

func (x *TaskRequest) GetC2ServerId() string {
	if x != nil {
		return x.C2ServerId
	}
	return ""
}

func (x *TaskRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskRequest) GetOriginalParams() string {
	if x != nil {
		return x.OriginalParams
	}
	return ""
}

func (x *TaskRequest) GetDisplayParams() string {
	if x != nil {
		return x.DisplayParams
	}
	return ""
}

func (x *TaskRequest) GetTimeStarted() string {
	if x != nil {
		return x.TimeStarted
	}
	return ""
}

func (x *TaskRequest) GetTimeCompleted() string {
	if x != nil {
		return x.TimeCompleted
	}
	return ""
}

func (x *TaskRequest) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *TaskRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *TaskRequest) GetInternalImplantId() string {
	if x != nil {
		return x.InternalImplantId
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{12}
}

type Process struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProcessId       int32                  `protobuf:"varint,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Architecture    string                 `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	User            string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	BinPath         string                 `protobuf:"bytes,5,opt,name=bin_path,json=binPath,proto3" json:"bin_path,omitempty"`
	ParentProcessId int32                  `protobuf:"varint,6,opt,name=parent_process_id,json=parentProcessId,proto3" json:"parent_process_id,omitempty"`
	CommandLine     string                 `protobuf:"bytes,7,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Handle          string                 `protobuf:"bytes,9,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *Process) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *Process) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Process) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Process) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Process) GetBinPath() string {
	if x != nil {
		return x.BinPath
	}
	return ""
}

func (x *Process) GetParentProcessId() int32 {
	if x != nil {
		return x.ParentProcessId
	}
	return 0
}

func (x *Process) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *Process) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Process) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type ShareFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	LastAccessed  string                 `protobuf:"bytes,3,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	LastModified  string                 `protobuf:"bytes,4,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	Created       string                 `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	UncPath       string                 `protobuf:"bytes,6,opt,name=unc_path,json=uncPath,proto3" json:"unc_path,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareFile) Reset() {
	*x = ShareFile{}
	mi := &file_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareFile) ProtoMessage() {}

func (x *ShareFile) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareFile.ProtoReflect.Descriptor instead.
func (*ShareFile) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ShareFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ShareFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ShareFile) GetLastAccessed() string {
	if x != nil {
		return x.LastAccessed
	}
	return ""
}

func (x *ShareFile) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

func (x *ShareFile) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *ShareFile) GetUncPath() string {
	if x != nil {
		return x.UncPath
	}
	return ""
}

func (x *ShareFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	ParentPath    string                 `protobuf:"bytes,2,opt,name=parent_path,json=parentPath,proto3" json:"parent_path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	UncPath       string                 `protobuf:"bytes,4,opt,name=unc_path,json=uncPath,proto3" json:"unc_path,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	LastAccessed  string                 `protobuf:"bytes,6,opt,name=last_accessed,json=lastAccessed,proto3" json:"last_accessed,omitempty"`
	LastModified  string                 `protobuf:"bytes,7,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	Created       string                 `protobuf:"bytes,8,opt,name=created,proto3" json:"created,omitempty"`
	Files         []*ShareFile           `protobuf:"bytes,10,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileList) Reset() {
	*x = FileList{}
	mi := &file_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileList) ProtoMessage() {}

func (x *FileList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileList.ProtoReflect.Descriptor instead.
func (*FileList) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *FileList) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *FileList) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *FileList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileList) GetUncPath() string {
	if x != nil {
		return x.UncPath
	}
	return ""
}

func (x *FileList) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileList) GetLastAccessed() string {
	if x != nil {
		return x.LastAccessed
	}
	return ""
}

func (x *FileList) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

func (x *FileList) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *FileList) GetFiles() []*ShareFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type TaskOutputRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InternalId     string                 `protobuf:"bytes,1,opt,name=internal_id,json=internalId,proto3" json:"internal_id,omitempty"`
	C2ServerId     string                 `protobuf:"bytes,2,opt,name=c2_server_id,json=c2ServerId,proto3" json:"c2_server_id,omitempty"`
	ResponseText   string                 `protobuf:"bytes,3,opt,name=response_text,json=responseText,proto3" json:"response_text,omitempty"`
	OutputType     string                 `protobuf:"bytes,4,opt,name=output_type,json=outputType,proto3" json:"output_type,omitempty"`
	Timestamp      string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InternalTaskId string                 `protobuf:"bytes,6,opt,name=internal_task_id,json=internalTaskId,proto3" json:"internal_task_id,omitempty"`
	Bucket         string                 `protobuf:"bytes,7,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Path           string                 `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	Processes      []*Process             `protobuf:"bytes,9,rep,name=processes,proto3" json:"processes,omitempty"`
	// repeated ShareFile files = 10;
	FileList      *FileList `protobuf:"bytes,11,opt,name=file_list,json=fileList,proto3" json:"file_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutputRequest) Reset() {
	*x = TaskOutputRequest{}
	mi := &file_v1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutputRequest) ProtoMessage() {}

func (x *TaskOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutputRequest.ProtoReflect.Descriptor instead.
func (*TaskOutputRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *TaskOutputRequest) GetInternalId() string {
	if x != nil {
		return x.InternalId
	}
	return ""
}

func (x *TaskOutputRequest) GetC2ServerId() string {
	if x != nil {
		return x.C2ServerId
	}
	return ""
}

func (x *TaskOutputRequest) GetResponseText() string {
	if x != nil {
		return x.ResponseText
	}
	return ""
}

func (x *TaskOutputRequest) GetOutputType() string {
	if x != nil {
		return x.OutputType
	}
	return ""
}

func (x *TaskOutputRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TaskOutputRequest) GetInternalTaskId() string {
	if x != nil {
		return x.InternalTaskId
	}
	return ""
}

func (x *TaskOutputRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *TaskOutputRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TaskOutputRequest) GetProcesses() []*Process {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *TaskOutputRequest) GetFileList() *FileList {
	if x != nil {
		return x.FileList
	}
	return nil
}

type TaskOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutputResponse) Reset() {
	*x = TaskOutputResponse{}
	mi := &file_v1_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutputResponse) ProtoMessage() {}

func (x *TaskOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutputResponse.ProtoReflect.Descriptor instead.
func (*TaskOutputResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{17}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_v1_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ChainStatus   string                 `protobuf:"bytes,4,opt,name=chain_status,json=chainStatus,proto3" json:"chain_status,omitempty"`
	Progress      *Progress              `protobuf:"bytes,5,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_v1_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *Event) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetChainStatus() string {
	if x != nil {
		return x.ChainStatus
	}
	return ""
}

func (x *Event) GetProgress() *Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Current       int32                  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Max           int32                  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Percentage    float32                `protobuf:"fixed32,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_v1_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *Progress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Progress) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Progress) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Progress) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Progress) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Progress) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Arguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arguments     []string               `protobuf:"bytes,1,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arguments) Reset() {
	*x = Arguments{}
	mi := &file_v1_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arguments) ProtoMessage() {}

func (x *Arguments) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arguments.ProtoReflect.Descriptor instead.
func (*Arguments) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{21}
}

func (x *Arguments) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type          OutputType             `protobuf:"varint,4,opt,name=type,proto3,enum=harbinger.go.proto.v1.OutputType" json:"type,omitempty"`
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_v1_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{22}
}

func (x *Output) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Output) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Output) GetType() OutputType {
	if x != nil {
		return x.Type
	}
	return OutputType_OUTPUT_TYPE_UNSPECIFIED
}

func (x *Output) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Output) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type FileExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Md5           string                 `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
	Sha1          string                 `protobuf:"bytes,2,opt,name=sha1,proto3" json:"sha1,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileExistsRequest) Reset() {
	*x = FileExistsRequest{}
	mi := &file_v1_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileExistsRequest) ProtoMessage() {}

func (x *FileExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileExistsRequest.ProtoReflect.Descriptor instead.
func (*FileExistsRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{23}
}

func (x *FileExistsRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *FileExistsRequest) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *FileExistsRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type FileExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileExistsResponse) Reset() {
	*x = FileExistsResponse{}
	mi := &file_v1_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileExistsResponse) ProtoMessage() {}

func (x *FileExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileExistsResponse.ProtoReflect.Descriptor instead.
func (*FileExistsResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{24}
}

func (x *FileExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_v1_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{25}
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadFileId  string                 `protobuf:"bytes,1,opt,name=upload_file_id,json=uploadFileId,proto3" json:"upload_file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_v1_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{26}
}

func (x *UploadFileResponse) GetUploadFileId() string {
	if x != nil {
		return x.UploadFileId
	}
	return ""
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_v1_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{27}
}

func (x *DownloadFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_v1_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{28}
}

func (x *DownloadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type C2ServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2ServerId    string                 `protobuf:"bytes,1,opt,name=c2_server_id,json=c2ServerId,proto3" json:"c2_server_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2ServerStatusRequest) Reset() {
	*x = C2ServerStatusRequest{}
	mi := &file_v1_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2ServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2ServerStatusRequest) ProtoMessage() {}

func (x *C2ServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2ServerStatusRequest.ProtoReflect.Descriptor instead.
func (*C2ServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{29}
}

func (x *C2ServerStatusRequest) GetC2ServerId() string {
	if x != nil {
		return x.C2ServerId
	}
	return ""
}

func (x *C2ServerStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *C2ServerStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type C2ServerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2ServerStatusResponse) Reset() {
	*x = C2ServerStatusResponse{}
	mi := &file_v1_messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2ServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2ServerStatusResponse) ProtoMessage() {}

func (x *C2ServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2ServerStatusResponse.ProtoReflect.Descriptor instead.
func (*C2ServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_messages_proto_rawDescGZIP(), []int{30}
}

var File_v1_messages_proto protoreflect.FileDescriptor

const file_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x11v1/messages.proto\x12\x15harbinger.go.proto.v1\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xf7\x03\n" +
	"\x0eImplantRequest\x12 \n" +
	"\fc2_server_id\x18\x01 \x01(\tR\n" +
	"c2ServerId\x12\x1f\n" +
	"\vinternal_id\x18\x02 \x01(\tR\n" +
	"internalId\x12\x17\n" +
	"\ac2_type\x18\x03 \x01(\tR\x06c2Type\x12!\n" +
	"\fpayload_type\x18\x04 \x01(\tR\vpayloadType\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x14\n" +
	"\x05sleep\x18\b \x01(\x05R\x05sleep\x12\x16\n" +
	"\x06jitter\x18\t \x01(\x05R\x06jitter\x12\x0e\n" +
	"\x02os\x18\n" +
	" \x01(\tR\x02os\x12\x10\n" +
	"\x03pid\x18\v \x01(\x05R\x03pid\x12\"\n" +
	"\farchitecture\x18\f \x01(\tR\farchitecture\x12\x18\n" +
	"\aprocess\x18\r \x01(\tR\aprocess\x12\x1a\n" +
	"\busername\x18\x0e \x01(\tR\busername\x12\x0e\n" +
	"\x02ip\x18\x0f \x01(\tR\x02ip\x12\x1f\n" +
	"\vexternal_ip\x18\x10 \x01(\tR\n" +
	"externalIp\x12\x16\n" +
	"\x06domain\x18\x11 \x01(\tR\x06domain\x12!\n" +
	"\flast_checkin\x18\x12 \x01(\tR\vlastCheckin\"\x11\n" +
	"\x0fImplantResponse\"\x9a\x02\n" +
	"\fProxyRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12'\n" +
	"\x0fremote_hostname\x18\x06 \x01(\tR\x0eremoteHostname\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\x12 \n" +
	"\fc2_server_id\x18\t \x01(\tR\n" +
	"c2ServerId\x12\x1f\n" +
	"\vinternal_id\x18\n" +
	" \x01(\tR\n" +
	"internalId\"\x0f\n" +
	"\rProxyResponse\"\xf7\x01\n" +
	"\vFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12(\n" +
	"\x10internal_task_id\x18\x04 \x01(\tR\x0einternalTaskId\x12 \n" +
	"\fc2_server_id\x18\x05 \x01(\tR\n" +
	"c2ServerId\x12.\n" +
	"\x13internal_implant_id\x18\x06 \x01(\tR\x11internalImplantId\x12$\n" +
	"\x0eupload_file_id\x18\a \x01(\tR\fuploadFileId\"\x1e\n" +
	"\fFileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x87\x01\n" +
	"\x13C2TaskStatusRequest\x12 \n" +
	"\fc2_server_id\x18\x01 \x01(\tR\n" +
	"c2ServerId\x12\x1c\n" +
	"\n" +
	"c2_task_id\x18\x02 \x01(\tR\bc2TaskId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x16\n" +
	"\x14C2TaskStatusResponse\"3\n" +
	"\x0fSettingsRequest\x12 \n" +
	"\fc2_server_id\x18\x01 \x01(\tR\n" +
	"c2ServerId\"\xa2\x02\n" +
	"\x10SettingsResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12%\n" +
	"\x0eca_certificate\x18\a \x01(\tR\rcaCertificate\x12\x1f\n" +
	"\vprivate_key\x18\b \x01(\tR\n" +
	"privateKey\x12\x14\n" +
	"\x05token\x18\t \x01(\tR\x05token\x12 \n" +
	"\vcertificate\x18\n" +
	" \x01(\tR\vcertificate\"\xf1\x02\n" +
	"\vTaskRequest\x12\x1f\n" +
	"\vinternal_id\x18\x01 \x01(\tR\n" +
	"internalId\x12 \n" +
	"\fc2_server_id\x18\x02 \x01(\tR\n" +
	"c2ServerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0foriginal_params\x18\x04 \x01(\tR\x0eoriginalParams\x12%\n" +
	"\x0edisplay_params\x18\x05 \x01(\tR\rdisplayParams\x12!\n" +
	"\ftime_started\x18\x06 \x01(\tR\vtimeStarted\x12%\n" +
	"\x0etime_completed\x18\a \x01(\tR\rtimeCompleted\x12!\n" +
	"\fcommand_name\x18\b \x01(\tR\vcommandName\x12\x1a\n" +
	"\boperator\x18\t \x01(\tR\boperator\x12.\n" +
	"\x13internal_implant_id\x18\n" +
	" \x01(\tR\x11internalImplantId\"\x0e\n" +
	"\fTaskResponse\"\x98\x02\n" +
	"\aProcess\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\x05R\tprocessId\x12\"\n" +
	"\farchitecture\x18\x02 \x01(\tR\farchitecture\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x19\n" +
	"\bbin_path\x18\x05 \x01(\tR\abinPath\x12*\n" +
	"\x11parent_process_id\x18\x06 \x01(\x05R\x0fparentProcessId\x12!\n" +
	"\fcommand_line\x18\a \x01(\tR\vcommandLine\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x16\n" +
	"\x06handle\x18\t \x01(\tR\x06handle\"\xc6\x01\n" +
	"\tShareFile\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12#\n" +
	"\rlast_accessed\x18\x03 \x01(\tR\flastAccessed\x12#\n" +
	"\rlast_modified\x18\x04 \x01(\tR\flastModified\x12\x18\n" +
	"\acreated\x18\x05 \x01(\tR\acreated\x12\x19\n" +
	"\bunc_path\x18\x06 \x01(\tR\auncPath\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\"\x9e\x02\n" +
	"\bFileList\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1f\n" +
	"\vparent_path\x18\x02 \x01(\tR\n" +
	"parentPath\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bunc_path\x18\x04 \x01(\tR\auncPath\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12#\n" +
	"\rlast_accessed\x18\x06 \x01(\tR\flastAccessed\x12#\n" +
	"\rlast_modified\x18\a \x01(\tR\flastModified\x12\x18\n" +
	"\acreated\x18\b \x01(\tR\acreated\x126\n" +
	"\x05files\x18\n" +
	" \x03(\v2 .harbinger.go.proto.v1.ShareFileR\x05files\"\x8c\x03\n" +
	"\x11TaskOutputRequest\x12\x1f\n" +
	"\vinternal_id\x18\x01 \x01(\tR\n" +
	"internalId\x12 \n" +
	"\fc2_server_id\x18\x02 \x01(\tR\n" +
	"c2ServerId\x12#\n" +
	"\rresponse_text\x18\x03 \x01(\tR\fresponseText\x12\x1f\n" +
	"\voutput_type\x18\x04 \x01(\tR\n" +
	"outputType\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12(\n" +
	"\x10internal_task_id\x18\x06 \x01(\tR\x0einternalTaskId\x12\x16\n" +
	"\x06bucket\x18\a \x01(\tR\x06bucket\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12<\n" +
	"\tprocesses\x18\t \x03(\v2\x1e.harbinger.go.proto.v1.ProcessR\tprocesses\x12<\n" +
	"\tfile_list\x18\v \x01(\v2\x1f.harbinger.go.proto.v1.FileListR\bfileList\"\x14\n" +
	"\x12TaskOutputResponse\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa1\x01\n" +
	"\x05Event\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fchain_status\x18\x04 \x01(\tR\vchainStatus\x12;\n" +
	"\bprogress\x18\x05 \x01(\v2\x1f.harbinger.go.proto.v1.ProgressR\bprogress\"\x9c\x01\n" +
	"\bProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x05R\acurrent\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x05R\x03max\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x02R\n" +
	"percentage\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\")\n" +
	"\tArguments\x12\x1c\n" +
	"\targuments\x18\x01 \x03(\tR\targuments\"\x9d\x01\n" +
	"\x06Output\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x125\n" +
	"\x04type\x18\x04 \x01(\x0e2!.harbinger.go.proto.v1.OutputTypeR\x04type\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"Q\n" +
	"\x11FileExistsRequest\x12\x10\n" +
	"\x03md5\x18\x01 \x01(\tR\x03md5\x12\x12\n" +
	"\x04sha1\x18\x02 \x01(\tR\x04sha1\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\",\n" +
	"\x12FileExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"'\n" +
	"\x11UploadFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\":\n" +
	"\x12UploadFileResponse\x12$\n" +
	"\x0eupload_file_id\x18\x01 \x01(\tR\fuploadFileId\".\n" +
	"\x13DownloadFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"*\n" +
	"\x14DownloadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"e\n" +
	"\x15C2ServerStatusRequest\x12 \n" +
	"\fc2_server_id\x18\x01 \x01(\tR\n" +
	"c2ServerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x18\n" +
	"\x16C2ServerStatusResponse*Y\n" +
	"\n" +
	"OutputType\x12\x1b\n" +
	"\x17OUTPUT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12OUTPUT_TYPE_STDOUT\x10\x01\x12\x16\n" +
	"\x12OUTPUT_TYPE_STDERR\x10\x022\xae\t\n" +
	"\tHarbinger\x12Q\n" +
	"\x04Ping\x12\".harbinger.go.proto.v1.PingRequest\x1a#.harbinger.go.proto.v1.PingResponse\"\x00\x12^\n" +
	"\vSaveImplant\x12%.harbinger.go.proto.v1.ImplantRequest\x1a&.harbinger.go.proto.v1.ImplantResponse\"\x00\x12X\n" +
	"\tSaveProxy\x12#.harbinger.go.proto.v1.ProxyRequest\x1a$.harbinger.go.proto.v1.ProxyResponse\"\x00\x12U\n" +
	"\bSaveFile\x12\".harbinger.go.proto.v1.FileRequest\x1a#.harbinger.go.proto.v1.FileResponse\"\x00\x12i\n" +
	"\fC2TaskStatus\x12*.harbinger.go.proto.v1.C2TaskStatusRequest\x1a+.harbinger.go.proto.v1.C2TaskStatusResponse\"\x00\x12`\n" +
	"\vGetSettings\x12&.harbinger.go.proto.v1.SettingsRequest\x1a'.harbinger.go.proto.v1.SettingsResponse\"\x00\x12U\n" +
	"\bSaveTask\x12\".harbinger.go.proto.v1.TaskRequest\x1a#.harbinger.go.proto.v1.TaskResponse\"\x00\x12g\n" +
	"\x0eSaveTaskOutput\x12(.harbinger.go.proto.v1.TaskOutputRequest\x1a).harbinger.go.proto.v1.TaskOutputResponse\"\x00\x12h\n" +
	"\x0fCheckFileExists\x12(.harbinger.go.proto.v1.FileExistsRequest\x1a).harbinger.go.proto.v1.FileExistsResponse\"\x00\x12e\n" +
	"\n" +
	"UploadFile\x12(.harbinger.go.proto.v1.UploadFileRequest\x1a).harbinger.go.proto.v1.UploadFileResponse\"\x00(\x01\x12k\n" +
	"\fDownloadFile\x12*.harbinger.go.proto.v1.DownloadFileRequest\x1a+.harbinger.go.proto.v1.DownloadFileResponse\"\x000\x01\x12r\n" +
	"\x11SetC2ServerStatus\x12,.harbinger.go.proto.v1.C2ServerStatusRequest\x1a-.harbinger.go.proto.v1.C2ServerStatusResponse\"\x00B6Z4github.com/mandiant/harbinger/go/proto/v1;messagesv1b\x06proto3"

var (
	file_v1_messages_proto_rawDescOnce sync.Once
	file_v1_messages_proto_rawDescData []byte
)

func file_v1_messages_proto_rawDescGZIP() []byte {
	file_v1_messages_proto_rawDescOnce.Do(func() {
		file_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_messages_proto_rawDesc), len(file_v1_messages_proto_rawDesc)))
	})
	return file_v1_messages_proto_rawDescData
}

var file_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_v1_messages_proto_goTypes = []any{
	(OutputType)(0),                // 0: harbinger.go.proto.v1.OutputType
	(*PingRequest)(nil),            // 1: harbinger.go.proto.v1.PingRequest
	(*ImplantRequest)(nil),         // 2: harbinger.go.proto.v1.ImplantRequest
	(*ImplantResponse)(nil),        // 3: harbinger.go.proto.v1.ImplantResponse
	(*ProxyRequest)(nil),           // 4: harbinger.go.proto.v1.ProxyRequest
	(*ProxyResponse)(nil),          // 5: harbinger.go.proto.v1.ProxyResponse
	(*FileRequest)(nil),            // 6: harbinger.go.proto.v1.FileRequest
	(*FileResponse)(nil),           // 7: harbinger.go.proto.v1.FileResponse
	(*C2TaskStatusRequest)(nil),    // 8: harbinger.go.proto.v1.C2TaskStatusRequest
	(*C2TaskStatusResponse)(nil),   // 9: harbinger.go.proto.v1.C2TaskStatusResponse
	(*SettingsRequest)(nil),        // 10: harbinger.go.proto.v1.SettingsRequest
	(*SettingsResponse)(nil),       // 11: harbinger.go.proto.v1.SettingsResponse
	(*TaskRequest)(nil),            // 12: harbinger.go.proto.v1.TaskRequest
	(*TaskResponse)(nil),           // 13: harbinger.go.proto.v1.TaskResponse
	(*Process)(nil),                // 14: harbinger.go.proto.v1.Process
	(*ShareFile)(nil),              // 15: harbinger.go.proto.v1.ShareFile
	(*FileList)(nil),               // 16: harbinger.go.proto.v1.FileList
	(*TaskOutputRequest)(nil),      // 17: harbinger.go.proto.v1.TaskOutputRequest
	(*TaskOutputResponse)(nil),     // 18: harbinger.go.proto.v1.TaskOutputResponse
	(*PingResponse)(nil),           // 19: harbinger.go.proto.v1.PingResponse
	(*Event)(nil),                  // 20: harbinger.go.proto.v1.Event
	(*Progress)(nil),               // 21: harbinger.go.proto.v1.Progress
	(*Arguments)(nil),              // 22: harbinger.go.proto.v1.Arguments
	(*Output)(nil),                 // 23: harbinger.go.proto.v1.Output
	(*FileExistsRequest)(nil),      // 24: harbinger.go.proto.v1.FileExistsRequest
	(*FileExistsResponse)(nil),     // 25: harbinger.go.proto.v1.FileExistsResponse
	(*UploadFileRequest)(nil),      // 26: harbinger.go.proto.v1.UploadFileRequest
	(*UploadFileResponse)(nil),     // 27: harbinger.go.proto.v1.UploadFileResponse
	(*DownloadFileRequest)(nil),    // 28: harbinger.go.proto.v1.DownloadFileRequest
	(*DownloadFileResponse)(nil),   // 29: harbinger.go.proto.v1.DownloadFileResponse
	(*C2ServerStatusRequest)(nil),  // 30: harbinger.go.proto.v1.C2ServerStatusRequest
	(*C2ServerStatusResponse)(nil), // 31: harbinger.go.proto.v1.C2ServerStatusResponse
}
var file_v1_messages_proto_depIdxs = []int32{
	15, // 0: harbinger.go.proto.v1.FileList.files:type_name -> harbinger.go.proto.v1.ShareFile
	14, // 1: harbinger.go.proto.v1.TaskOutputRequest.processes:type_name -> harbinger.go.proto.v1.Process
	16, // 2: harbinger.go.proto.v1.TaskOutputRequest.file_list:type_name -> harbinger.go.proto.v1.FileList
	21, // 3: harbinger.go.proto.v1.Event.progress:type_name -> harbinger.go.proto.v1.Progress
	0,  // 4: harbinger.go.proto.v1.Output.type:type_name -> harbinger.go.proto.v1.OutputType
	1,  // 5: harbinger.go.proto.v1.Harbinger.Ping:input_type -> harbinger.go.proto.v1.PingRequest
	2,  // 6: harbinger.go.proto.v1.Harbinger.SaveImplant:input_type -> harbinger.go.proto.v1.ImplantRequest
	4,  // 7: harbinger.go.proto.v1.Harbinger.SaveProxy:input_type -> harbinger.go.proto.v1.ProxyRequest
	6,  // 8: harbinger.go.proto.v1.Harbinger.SaveFile:input_type -> harbinger.go.proto.v1.FileRequest
	8,  // 9: harbinger.go.proto.v1.Harbinger.C2TaskStatus:input_type -> harbinger.go.proto.v1.C2TaskStatusRequest
	10, // 10: harbinger.go.proto.v1.Harbinger.GetSettings:input_type -> harbinger.go.proto.v1.SettingsRequest
	12, // 11: harbinger.go.proto.v1.Harbinger.SaveTask:input_type -> harbinger.go.proto.v1.TaskRequest
	17, // 12: harbinger.go.proto.v1.Harbinger.SaveTaskOutput:input_type -> harbinger.go.proto.v1.TaskOutputRequest
	24, // 13: harbinger.go.proto.v1.Harbinger.CheckFileExists:input_type -> harbinger.go.proto.v1.FileExistsRequest
	26, // 14: harbinger.go.proto.v1.Harbinger.UploadFile:input_type -> harbinger.go.proto.v1.UploadFileRequest
	28, // 15: harbinger.go.proto.v1.Harbinger.DownloadFile:input_type -> harbinger.go.proto.v1.DownloadFileRequest
	30, // 16: harbinger.go.proto.v1.Harbinger.SetC2ServerStatus:input_type -> harbinger.go.proto.v1.C2ServerStatusRequest
	19, // 17: harbinger.go.proto.v1.Harbinger.Ping:output_type -> harbinger.go.proto.v1.PingResponse
	3,  // 18: harbinger.go.proto.v1.Harbinger.SaveImplant:output_type -> harbinger.go.proto.v1.ImplantResponse
	5,  // 19: harbinger.go.proto.v1.Harbinger.SaveProxy:output_type -> harbinger.go.proto.v1.ProxyResponse
	7,  // 20: harbinger.go.proto.v1.Harbinger.SaveFile:output_type -> harbinger.go.proto.v1.FileResponse
	9,  // 21: harbinger.go.proto.v1.Harbinger.C2TaskStatus:output_type -> harbinger.go.proto.v1.C2TaskStatusResponse
	11, // 22: harbinger.go.proto.v1.Harbinger.GetSettings:output_type -> harbinger.go.proto.v1.SettingsResponse
	13, // 23: harbinger.go.proto.v1.Harbinger.SaveTask:output_type -> harbinger.go.proto.v1.TaskResponse
	18, // 24: harbinger.go.proto.v1.Harbinger.SaveTaskOutput:output_type -> harbinger.go.proto.v1.TaskOutputResponse
	25, // 25: harbinger.go.proto.v1.Harbinger.CheckFileExists:output_type -> harbinger.go.proto.v1.FileExistsResponse
	27, // 26: harbinger.go.proto.v1.Harbinger.UploadFile:output_type -> harbinger.go.proto.v1.UploadFileResponse
	29, // 27: harbinger.go.proto.v1.Harbinger.DownloadFile:output_type -> harbinger.go.proto.v1.DownloadFileResponse
	31, // 28: harbinger.go.proto.v1.Harbinger.SetC2ServerStatus:output_type -> harbinger.go.proto.v1.C2ServerStatusResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_messages_proto_init() }
func file_v1_messages_proto_init() {
	if File_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_messages_proto_rawDesc), len(file_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_messages_proto_goTypes,
		DependencyIndexes: file_v1_messages_proto_depIdxs,
		EnumInfos:         file_v1_messages_proto_enumTypes,
		MessageInfos:      file_v1_messages_proto_msgTypes,
	}.Build()
	File_v1_messages_proto = out.File
	file_v1_messages_proto_goTypes = nil
	file_v1_messages_proto_depIdxs = nil
}
