"""Add docker_image to proxy_jobs

Revision ID: 967c6a4874ab
Revises: 81979e384557
Create Date: 2025-10-08 11:17:08.844451

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "967c6a4874ab"
down_revision = "81979e384557"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("proxy_jobs", sa.Column("docker_image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proxy_jobs", "docker_image")
    # ### end Alembic commands ###
