"""Add manual_timeline_task_id to File

Revision ID: dc0da548d27a
Revises: 891e7a1f123d
Create Date: 2025-07-18 06:24:25.895948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0da548d27a'
down_revision = '891e7a1f123d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('manual_timeline_task_id', sa.UUID(), nullable=True))
    op.create_foreign_key('files_manual_timeline_tasks_fk', 'files', 'manual_timeline_tasks', ['manual_timeline_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_manual_timeline_tasks_fk', 'files', type_='foreignkey')
    op.drop_column('files', 'manual_timeline_task_id')
    # ### end Alembic commands ###
