# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""initial database init

Revision ID: eac63cedd02c
Revises:
Create Date: 2025-03-06 08:16:14.836212

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eac63cedd02c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_completed", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "c2_server_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("docker_image", sa.String(), nullable=True),
        sa.Column("command", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "c2_servers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("hostname", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("ca_certificate", sa.String(), nullable=True),
        sa.Column("certificate", sa.String(), nullable=True),
        sa.Column("private_key", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "certificate_authorities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ca_name", sa.String(), nullable=True),
        sa.Column("dns_name", sa.String(), nullable=True),
        sa.Column("certificate_subject", sa.String(), nullable=True),
        sa.Column("certificate_serial_number", sa.String(), nullable=True),
        sa.Column("certificate_validity_start", sa.String(), nullable=True),
        sa.Column("certificate_validity_end", sa.String(), nullable=True),
        sa.Column("web_enrollment", sa.String(), nullable=True),
        sa.Column("user_specified_san", sa.String(), nullable=True),
        sa.Column("request_disposition", sa.String(), nullable=True),
        sa.Column("enforce_encryption_for_requests", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ca_name", "dns_name", name="ca_dns_name_uc"),
    )
    op.create_table(
        "certificate_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("template_name", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("client_authentication", sa.Boolean(), nullable=True),
        sa.Column("enrollment_agent", sa.Boolean(), nullable=True),
        sa.Column("any_purpose", sa.Boolean(), nullable=True),
        sa.Column("enrollee_supplies_subject", sa.Boolean(), nullable=True),
        sa.Column("requires_manager_approval", sa.Boolean(), nullable=True),
        sa.Column("requires_manager_archival", sa.Boolean(), nullable=True),
        sa.Column("authorized_signatures_required", sa.Integer(), nullable=True),
        sa.Column("validity_period", sa.String(), nullable=True),
        sa.Column("renewal_period", sa.String(), nullable=True),
        sa.Column("minimum_rsa_key_length", sa.Integer(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "components",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("hostname", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "time_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "domains",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.Column("long_name", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("long_name"),
        sa.UniqueConstraint("short_name"),
    )
    op.create_table(
        "hashes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("hash", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("hashcat_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("sha256_hash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256_hash"),
    )
    op.create_table(
        "kerberos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client", sa.String(), nullable=True),
        sa.Column("server", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("keytype", sa.String(), nullable=True),
        sa.Column("auth", sa.DateTime(), nullable=True),
        sa.Column("start", sa.DateTime(), nullable=True),
        sa.Column("end", sa.DateTime(), nullable=True),
        sa.Column("renew", sa.DateTime(), nullable=True),
        sa.Column("ccache", sa.String(), nullable=True),
        sa.Column("kirbi", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "labels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "manual_timeline_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("arguments", sa.String(), nullable=True),
        sa.Column("time_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_completed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("command_name", sa.String(), nullable=True),
        sa.Column("operator", sa.String(), nullable=True),
        sa.Column("output", sa.String(), nullable=True),
        sa.Column("hostname", sa.String(), nullable=True),
        sa.Column("ai_summary", sa.String(), nullable=True),
        sa.Column("processing_status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "objectives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "passwords",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("nt", sa.String(), nullable=True),
        sa.Column("aes256_key", sa.String(), nullable=True),
        sa.Column("aes128_key", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playbook_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("tactic", sa.String(), nullable=True),
        sa.Column("technique", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("step_delay", sa.Integer(), nullable=True),
        sa.Column("yaml", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "setting_category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "socks_servers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("hostname", sa.String(), nullable=True),
        sa.Column("operating_system", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "action_playbook",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column("playbook_template_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playbook_template_id"],
            ["playbook_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "c2_implant_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("c2_server_type_id", sa.UUID(), nullable=False),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_server_type_id"],
            ["c2_server_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "c2_server_arguments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("regex", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("default", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("c2_server_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_server_type_id"],
            ["c2_server_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "c2_server_status",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("c2_server_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_server_id"],
            ["c2_servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "certificate_template_authority_map",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("certificate_authority_id", sa.UUID(), nullable=False),
        sa.Column("certificate_template_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["certificate_authority_id"],
            ["certificate_authorities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["certificate_template_id"],
            ["certificate_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "certificate_authority_id",
            "certificate_template_id",
            name="authority_template_id_uc",
        ),
    )
    op.create_table(
        "certificate_template_permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("certificate_template_id", sa.UUID(), nullable=False),
        sa.Column("permission", sa.String(), nullable=True),
        sa.Column("principal", sa.String(), nullable=True),
        sa.Column("principal_type", sa.String(), nullable=True),
        sa.Column("object_id", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["certificate_template_id"],
            ["certificate_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "certificate_template_id",
            "permission",
            "principal",
            name="certificate_template_permissions_uc",
        ),
    )
    op.create_table(
        "credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password_id", sa.UUID(), nullable=True),
        sa.Column("kerberos_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kerberos_id"],
            ["kerberos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["password_id"],
            ["passwords.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hosts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("objectid", sa.String(), nullable=True),
        sa.Column("owned", sa.Boolean(), nullable=True),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("fqdn", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain_id", "name", name="domain_host_name_uc"),
        sa.UniqueConstraint("fqdn"),
        sa.UniqueConstraint("objectid"),
    )
    op.create_table(
        "issues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("impact", sa.String(), nullable=True),
        sa.Column("exploitability", sa.String(), nullable=True),
        sa.Column("label_id", sa.UUID(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["labels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "playbooks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("playbook_name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("arguments", sa.JSON(), nullable=True),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("completed", sa.Integer(), nullable=True),
        sa.Column("playbook_template_id", sa.UUID(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_completed", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["playbook_template_id"],
            ["playbook_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["setting_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "category_id", name="name_category"),
    )
    op.create_table(
        "situational_awareness",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("value_string", sa.String(), nullable=True),
        sa.Column("value_int", sa.Integer(), nullable=True),
        sa.Column("value_bool", sa.Boolean(), nullable=True),
        sa.Column("value_json", sa.JSON(), nullable=True),
        sa.Column("domain_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "c2_implant_arguments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("c2_implant_type_id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_implant_type_id"],
            ["c2_implant_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "c2_implants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("c2_server_id", sa.UUID(), nullable=True),
        sa.Column("internal_id", sa.String(), nullable=True),
        sa.Column("c2_type", sa.String(), nullable=True),
        sa.Column("payload_type", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("hostname", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("sleep", sa.BigInteger(), nullable=True),
        sa.Column("jitter", sa.BigInteger(), nullable=True),
        sa.Column("os", sa.String(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("architecture", sa.String(), nullable=True),
        sa.Column("process", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("external_ip", sa.String(), nullable=True),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("last_checkin", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("host_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_server_id"],
            ["c2_servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("c2_server_id", "internal_id", name="c2_implants_uc"),
    )
    op.create_table(
        "ip_addresses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shares",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("host_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("unc_path", sa.String(), nullable=True),
        sa.Column("type", sa.BigInteger(), nullable=True),
        sa.Column("remark", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "name", name="share_host_name_uc"),
    )
    op.create_table(
        "c2_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("internal_id", sa.String(), nullable=True),
        sa.Column("c2_implant_id", sa.UUID(), nullable=True),
        sa.Column("c2_server_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("original_params", sa.String(), nullable=True),
        sa.Column("display_params", sa.String(), nullable=True),
        sa.Column("time_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_completed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("command_name", sa.String(), nullable=True),
        sa.Column("operator", sa.String(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("ai_summary", sa.String(), nullable=True),
        sa.Column("processing_status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_implant_id"],
            ["c2_implants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_server_id"],
            ["c2_servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("c2_server_id", "internal_id", name="c2_tasks_uc"),
    )
    op.create_table(
        "checklist",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=True),
        sa.Column("c2_implant_id", sa.UUID(), nullable=True),
        sa.Column("phase", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_implant_id"],
            ["c2_implants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "c2_implant_id", "phase", "name", name="checklist_implant_phase_name"
        ),
        sa.UniqueConstraint(
            "domain_id", "phase", "name", name="checklist_domain_phase_name"
        ),
    )
    op.create_table(
        "processes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=True),
        sa.Column("architecture", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("bin_path", sa.String(), nullable=True),
        sa.Column("parent_process_id", sa.Integer(), nullable=True),
        sa.Column("command_line", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("handle", sa.String(), nullable=True),
        sa.Column("host_id", sa.UUID(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("c2_implant_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_implant_id"],
            ["c2_implants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suggestions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("playbook_template_id", sa.UUID(), nullable=True),
        sa.Column("c2_implant_id", sa.UUID(), nullable=True),
        sa.Column("command", sa.String(), nullable=True),
        sa.Column("arguments", sa.JSON(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_implant_id"],
            ["c2_implants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playbook_template_id"],
            ["playbook_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "c2_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("c2_type", sa.String(), nullable=True),
        sa.Column("c2_task_id", sa.UUID(), nullable=True),
        sa.Column("c2_server_id", sa.UUID(), nullable=True),
        sa.Column("c2_implant_id", sa.UUID(), nullable=True),
        sa.Column("command", sa.String(), nullable=True),
        sa.Column("arguments", sa.String(), nullable=True),
        sa.Column("playbook_id", sa.UUID(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_completed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("add_labels", sa.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_implant_id"],
            ["c2_implants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_server_id"],
            ["c2_servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_task_id"],
            ["c2_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playbook_id"],
            ["playbooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "c2_task_output",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("c2_implant_id", sa.UUID(), nullable=True),
        sa.Column("c2_task_id", sa.UUID(), nullable=True),
        sa.Column("c2_server_id", sa.UUID(), nullable=True),
        sa.Column("internal_id", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_text", sa.String(), nullable=True),
        sa.Column("response_bytes", sa.LargeBinary(), nullable=True),
        sa.Column("output_type", sa.String(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_implant_id"],
            ["c2_implants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_server_id"],
            ["c2_servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_task_id"],
            ["c2_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("c2_server_id", "internal_id", name="c2_output_uc"),
    )
    op.create_table(
        "proxies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("remote_hostname", sa.String(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("c2_server_id", sa.UUID(), nullable=True),
        sa.Column("internal_id", sa.String(), nullable=True),
        sa.Column("c2_implant_id", sa.UUID(), nullable=True),
        sa.Column("c2_task_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_implant_id"],
            ["c2_implants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_server_id"],
            ["c2_servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_task_id"],
            ["c2_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proxy_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.UUID(), nullable=True),
        sa.Column("proxy_id", sa.UUID(), nullable=True),
        sa.Column("socks_server_id", sa.UUID(), nullable=True),
        sa.Column("executor_type", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("command", sa.String(), nullable=True),
        sa.Column("arguments", sa.String(), nullable=True),
        sa.Column("playbook_id", sa.UUID(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_completed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tmate", sa.Boolean(), nullable=True),
        sa.Column("asciinema", sa.Boolean(), nullable=True),
        sa.Column("proxychains", sa.Boolean(), nullable=True),
        sa.Column("env", sa.String(), nullable=True),
        sa.Column("ai_summary", sa.String(), nullable=True),
        sa.Column("processing_status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playbook_id"],
            ["playbooks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_id"],
            ["proxies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["socks_server_id"],
            ["socks_servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("bucket", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("filetype", sa.String(), nullable=True),
        sa.Column("magic_mimetype", sa.String(), nullable=True),
        sa.Column("magika_mimetype", sa.String(), nullable=True),
        sa.Column("exiftool", sa.String(), nullable=True),
        sa.Column("md5sum", sa.String(), nullable=True),
        sa.Column("sha1sum", sa.String(), nullable=True),
        sa.Column("sha256sum", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("processing_status", sa.String(), nullable=True),
        sa.Column("processing_progress", sa.Integer(), nullable=True),
        sa.Column("processing_note", sa.String(), nullable=True),
        sa.Column("c2_implant_id", sa.UUID(), nullable=True),
        sa.Column("c2_task_id", sa.UUID(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["c2_implant_id"],
            ["c2_implants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_task_id"],
            ["c2_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["proxy_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playbook_step",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("depends_on", sa.String(), nullable=True),
        sa.Column("playbook_id", sa.UUID(), nullable=True),
        sa.Column("proxy_job_id", sa.UUID(), nullable=True),
        sa.Column("c2_job_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("delay", sa.Interval(), nullable=True),
        sa.Column("execute_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_completed", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_job_id"],
            ["c2_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playbook_id"],
            ["playbooks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_job_id"],
            ["proxy_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proxy_job_output",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("output", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("output_type", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["proxy_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "input_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("c2_job_id", sa.UUID(), nullable=True),
        sa.Column("proxy_job_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_job_id"],
            ["c2_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_job_id"],
            ["proxy_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parse_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("parser", sa.String(), nullable=True),
        sa.Column("log", sa.String(), nullable=True),
        sa.Column("c2_task_id", sa.UUID(), nullable=True),
        sa.Column("c2_task_output_id", sa.UUID(), nullable=True),
        sa.Column("proxy_job_output_id", sa.UUID(), nullable=True),
        sa.Column("proxy_job_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_task_id"],
            ["c2_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_task_output_id"],
            ["c2_task_output.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_job_id"],
            ["proxy_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_job_output_id"],
            ["proxy_job_output.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playbook_step_modifier",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("regex", sa.String(), nullable=True),
        sa.Column("input_path", sa.String(), nullable=True),
        sa.Column("output_path", sa.String(), nullable=True),
        sa.Column("output_format", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("on_error", sa.String(), nullable=True),
        sa.Column("data", sa.String(), nullable=True),
        sa.Column("status_message", sa.String(), nullable=True),
        sa.Column("playbook_step_id", sa.UUID(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["playbook_step_id"],
            ["playbook_step.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "share_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("share_id", sa.UUID(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("last_accessed", sa.DateTime(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("unc_path", sa.String(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("extension", sa.String(), nullable=True),
        sa.Column("downloaded", sa.Boolean(), nullable=True),
        sa.Column("indexed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["share_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["share_id"],
            ["shares.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unc_path", name="share_files_unc_path"),
    )
    op.create_table(
        "highlights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("c2_task_id", sa.UUID(), nullable=True),
        sa.Column("c2_task_output_id", sa.UUID(), nullable=True),
        sa.Column("proxy_job_output_id", sa.UUID(), nullable=True),
        sa.Column("proxy_job_id", sa.UUID(), nullable=True),
        sa.Column("parse_result_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.Integer(), nullable=True),
        sa.Column("rule_type", sa.String(), nullable=True),
        sa.Column("hit", sa.String(), nullable=True),
        sa.Column("start", sa.Integer(), nullable=True),
        sa.Column("end", sa.Integer(), nullable=True),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["c2_task_id"],
            ["c2_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_task_output_id"],
            ["c2_task_output.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parse_result_id"],
            ["parse_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_job_id"],
            ["proxy_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_job_output_id"],
            ["proxy_job_output.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "labeled_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("label_id", sa.UUID(), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=True),
        sa.Column("password_id", sa.UUID(), nullable=True),
        sa.Column("kerberos_id", sa.UUID(), nullable=True),
        sa.Column("credential_id", sa.UUID(), nullable=True),
        sa.Column("proxy_id", sa.UUID(), nullable=True),
        sa.Column("proxy_job_id", sa.UUID(), nullable=True),
        sa.Column("proxy_job_output", sa.UUID(), nullable=True),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("playbook_id", sa.UUID(), nullable=True),
        sa.Column("playbook_step_id", sa.UUID(), nullable=True),
        sa.Column("c2_job_id", sa.UUID(), nullable=True),
        sa.Column("host_id", sa.UUID(), nullable=True),
        sa.Column("process_id", sa.UUID(), nullable=True),
        sa.Column("playbook_template_id", sa.UUID(), nullable=True),
        sa.Column("c2_server_id", sa.UUID(), nullable=True),
        sa.Column("c2_implant_id", sa.UUID(), nullable=True),
        sa.Column("c2_task_id", sa.UUID(), nullable=True),
        sa.Column("c2_task_output_id", sa.UUID(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("share_id", sa.UUID(), nullable=True),
        sa.Column("share_file_id", sa.UUID(), nullable=True),
        sa.Column("highlight_id", sa.UUID(), nullable=True),
        sa.Column("hash_id", sa.UUID(), nullable=True),
        sa.Column("parse_result_id", sa.UUID(), nullable=True),
        sa.Column("socks_server_id", sa.UUID(), nullable=True),
        sa.Column("action_id", sa.UUID(), nullable=True),
        sa.Column("certificate_authority_id", sa.UUID(), nullable=True),
        sa.Column("certificate_template_id", sa.UUID(), nullable=True),
        sa.Column("issue_id", sa.UUID(), nullable=True),
        sa.Column("manual_timeline_task_id", sa.UUID(), nullable=True),
        sa.Column("suggestion_id", sa.UUID(), nullable=True),
        sa.Column("checklist_id", sa.UUID(), nullable=True),
        sa.Column("objective_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_implant_id"],
            ["c2_implants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_job_id"],
            ["c2_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_server_id"],
            ["c2_servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_task_id"],
            ["c2_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["c2_task_output_id"],
            ["c2_task_output.id"],
        ),
        sa.ForeignKeyConstraint(
            ["certificate_authority_id"],
            ["certificate_authorities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["certificate_template_id"],
            ["certificate_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["checklist_id"],
            ["checklist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hash_id"],
            ["hashes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["highlight_id"],
            ["highlights.id"],
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["issue_id"],
            ["issues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kerberos_id"],
            ["kerberos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["labels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manual_timeline_task_id"],
            ["manual_timeline_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parse_result_id"],
            ["parse_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["password_id"],
            ["passwords.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playbook_id"],
            ["playbooks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playbook_step_id"],
            ["playbook_step.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playbook_template_id"],
            ["playbook_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["processes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_id"],
            ["proxies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_job_id"],
            ["proxy_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proxy_job_output"],
            ["proxy_job_output.id"],
        ),
        sa.ForeignKeyConstraint(
            ["share_file_id"],
            ["share_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["share_id"],
            ["shares.id"],
        ),
        sa.ForeignKeyConstraint(
            ["socks_server_id"],
            ["socks_servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suggestion_id"],
            ["suggestions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("labeled_item")
    op.drop_table("highlights")
    op.drop_table("share_files")
    op.drop_table("playbook_step_modifier")
    op.drop_table("parse_results")
    op.drop_table("input_files")
    op.drop_table("proxy_job_output")
    op.drop_table("playbook_step")
    op.drop_table("files")
    op.drop_table("proxy_jobs")
    op.drop_table("proxies")
    op.drop_table("c2_task_output")
    op.drop_table("c2_jobs")
    op.drop_table("suggestions")
    op.drop_table("processes")
    op.drop_table("checklist")
    op.drop_table("c2_tasks")
    op.drop_table("shares")
    op.drop_table("ip_addresses")
    op.drop_table("c2_implants")
    op.drop_table("c2_implant_arguments")
    op.drop_table("situational_awareness")
    op.drop_table("settings")
    op.drop_table("playbooks")
    op.drop_table("issues")
    op.drop_table("hosts")
    op.drop_table("credentials")
    op.drop_table("certificate_template_permissions")
    op.drop_table("certificate_template_authority_map")
    op.drop_table("c2_server_status")
    op.drop_table("c2_server_arguments")
    op.drop_table("c2_implant_types")
    op.drop_table("action_playbook")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("socks_servers")
    op.drop_table("setting_category")
    op.drop_table("playbook_templates")
    op.drop_table("passwords")
    op.drop_table("objectives")
    op.drop_table("manual_timeline_tasks")
    op.drop_table("labels")
    op.drop_table("kerberos")
    op.drop_table("hashes")
    op.drop_table("domains")
    op.drop_table("components")
    op.drop_table("certificate_templates")
    op.drop_table("certificate_authorities")
    op.drop_table("c2_servers")
    op.drop_table("c2_server_types")
    op.drop_table("actions")
    # ### end Alembic commands ###
