# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import messages_pb2 as v1_dot_messages__pb2


class HarbingerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/harbinger.go.proto.v1.Harbinger/Ping',
                request_serializer=v1_dot_messages__pb2.PingRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.PingResponse.FromString,
                )
        self.SaveImplant = channel.unary_unary(
                '/harbinger.go.proto.v1.Harbinger/SaveImplant',
                request_serializer=v1_dot_messages__pb2.ImplantRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.ImplantResponse.FromString,
                )
        self.SaveProxy = channel.unary_unary(
                '/harbinger.go.proto.v1.Harbinger/SaveProxy',
                request_serializer=v1_dot_messages__pb2.ProxyRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.ProxyResponse.FromString,
                )
        self.SaveFile = channel.unary_unary(
                '/harbinger.go.proto.v1.Harbinger/SaveFile',
                request_serializer=v1_dot_messages__pb2.FileRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.FileResponse.FromString,
                )
        self.C2TaskStatus = channel.unary_unary(
                '/harbinger.go.proto.v1.Harbinger/C2TaskStatus',
                request_serializer=v1_dot_messages__pb2.C2TaskStatusRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.C2TaskStatusResponse.FromString,
                )
        self.GetSettings = channel.unary_unary(
                '/harbinger.go.proto.v1.Harbinger/GetSettings',
                request_serializer=v1_dot_messages__pb2.SettingsRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.SettingsResponse.FromString,
                )
        self.SaveTask = channel.unary_unary(
                '/harbinger.go.proto.v1.Harbinger/SaveTask',
                request_serializer=v1_dot_messages__pb2.TaskRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.TaskResponse.FromString,
                )
        self.SaveTaskOutput = channel.unary_unary(
                '/harbinger.go.proto.v1.Harbinger/SaveTaskOutput',
                request_serializer=v1_dot_messages__pb2.TaskOutputRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.TaskOutputResponse.FromString,
                )
        self.CheckFileExists = channel.unary_unary(
                '/harbinger.go.proto.v1.Harbinger/CheckFileExists',
                request_serializer=v1_dot_messages__pb2.FileExistsRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.FileExistsResponse.FromString,
                )
        self.UploadFile = channel.stream_unary(
                '/harbinger.go.proto.v1.Harbinger/UploadFile',
                request_serializer=v1_dot_messages__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.UploadFileResponse.FromString,
                )
        self.DownloadFile = channel.unary_stream(
                '/harbinger.go.proto.v1.Harbinger/DownloadFile',
                request_serializer=v1_dot_messages__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.DownloadFileResponse.FromString,
                )
        self.SetC2ServerStatus = channel.unary_unary(
                '/harbinger.go.proto.v1.Harbinger/SetC2ServerStatus',
                request_serializer=v1_dot_messages__pb2.C2ServerStatusRequest.SerializeToString,
                response_deserializer=v1_dot_messages__pb2.C2ServerStatusResponse.FromString,
                )


class HarbingerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveImplant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveProxy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def C2TaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveTaskOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckFileExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetC2ServerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarbingerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=v1_dot_messages__pb2.PingRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.PingResponse.SerializeToString,
            ),
            'SaveImplant': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveImplant,
                    request_deserializer=v1_dot_messages__pb2.ImplantRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.ImplantResponse.SerializeToString,
            ),
            'SaveProxy': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveProxy,
                    request_deserializer=v1_dot_messages__pb2.ProxyRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.ProxyResponse.SerializeToString,
            ),
            'SaveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveFile,
                    request_deserializer=v1_dot_messages__pb2.FileRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.FileResponse.SerializeToString,
            ),
            'C2TaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.C2TaskStatus,
                    request_deserializer=v1_dot_messages__pb2.C2TaskStatusRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.C2TaskStatusResponse.SerializeToString,
            ),
            'GetSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSettings,
                    request_deserializer=v1_dot_messages__pb2.SettingsRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.SettingsResponse.SerializeToString,
            ),
            'SaveTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveTask,
                    request_deserializer=v1_dot_messages__pb2.TaskRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.TaskResponse.SerializeToString,
            ),
            'SaveTaskOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveTaskOutput,
                    request_deserializer=v1_dot_messages__pb2.TaskOutputRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.TaskOutputResponse.SerializeToString,
            ),
            'CheckFileExists': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckFileExists,
                    request_deserializer=v1_dot_messages__pb2.FileExistsRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.FileExistsResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=v1_dot_messages__pb2.UploadFileRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.UploadFileResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=v1_dot_messages__pb2.DownloadFileRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.DownloadFileResponse.SerializeToString,
            ),
            'SetC2ServerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetC2ServerStatus,
                    request_deserializer=v1_dot_messages__pb2.C2ServerStatusRequest.FromString,
                    response_serializer=v1_dot_messages__pb2.C2ServerStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'harbinger.go.proto.v1.Harbinger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Harbinger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harbinger.go.proto.v1.Harbinger/Ping',
            v1_dot_messages__pb2.PingRequest.SerializeToString,
            v1_dot_messages__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveImplant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harbinger.go.proto.v1.Harbinger/SaveImplant',
            v1_dot_messages__pb2.ImplantRequest.SerializeToString,
            v1_dot_messages__pb2.ImplantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveProxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harbinger.go.proto.v1.Harbinger/SaveProxy',
            v1_dot_messages__pb2.ProxyRequest.SerializeToString,
            v1_dot_messages__pb2.ProxyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harbinger.go.proto.v1.Harbinger/SaveFile',
            v1_dot_messages__pb2.FileRequest.SerializeToString,
            v1_dot_messages__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def C2TaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harbinger.go.proto.v1.Harbinger/C2TaskStatus',
            v1_dot_messages__pb2.C2TaskStatusRequest.SerializeToString,
            v1_dot_messages__pb2.C2TaskStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harbinger.go.proto.v1.Harbinger/GetSettings',
            v1_dot_messages__pb2.SettingsRequest.SerializeToString,
            v1_dot_messages__pb2.SettingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harbinger.go.proto.v1.Harbinger/SaveTask',
            v1_dot_messages__pb2.TaskRequest.SerializeToString,
            v1_dot_messages__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveTaskOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harbinger.go.proto.v1.Harbinger/SaveTaskOutput',
            v1_dot_messages__pb2.TaskOutputRequest.SerializeToString,
            v1_dot_messages__pb2.TaskOutputResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckFileExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harbinger.go.proto.v1.Harbinger/CheckFileExists',
            v1_dot_messages__pb2.FileExistsRequest.SerializeToString,
            v1_dot_messages__pb2.FileExistsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/harbinger.go.proto.v1.Harbinger/UploadFile',
            v1_dot_messages__pb2.UploadFileRequest.SerializeToString,
            v1_dot_messages__pb2.UploadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/harbinger.go.proto.v1.Harbinger/DownloadFile',
            v1_dot_messages__pb2.DownloadFileRequest.SerializeToString,
            v1_dot_messages__pb2.DownloadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetC2ServerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/harbinger.go.proto.v1.Harbinger/SetC2ServerStatus',
            v1_dot_messages__pb2.C2ServerStatusRequest.SerializeToString,
            v1_dot_messages__pb2.C2ServerStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
