name: Docker Image CI

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  build-docker:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: Dockerfile
            context: harbinger
          - dockerfile: Dockerfile.proxy
            context: harbinger
          - dockerfile: Dockerfile.mythic
            context: go
          - dockerfile: Dockerfile.events
            context: go
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:${{ matrix.context }}"
        push: false
        file: ${{ matrix.dockerfile }}
